### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by pirey** [emsifa/stuble#1]
![flameshot_2020-08-19_13-35-21](https://user-images.githubusercontent.com/10344542/90599929-e873fb00-e21f-11ea-8d95-5106c814fa4b.png)
Got uncaught type error when running `stuble make <directory>`

**Comment by emsifa** [comment]
Hello @pirey ,

This may be due to the `symfony/console` version being installed on global dependencies. Can you please show the output of command below:

```
composer global show | grep 'symfony/console'
```

**Comment by pirey** [comment]
![flameshot_2020-08-19_16-38-51](https://user-images.githubusercontent.com/10344542/90617946-7f997c80-e239-11ea-95b3-c414c0545981.png)

**Comment by emsifa** [comment]
I've updated `symfony/console` version in `v0.2.6`. Try command below to install newer version of stuble:

```
composer global require emsifa/stuble:0.2.6
```

If it shows dependencies conflict, you can try `composer remove emsifa/stuble` then install it again.

**Comment by pirey** [comment]
i have tried to remove and re-install stuble,
but now i got the following error:

![flameshot_2020-08-19_22-44-39](https://user-images.githubusercontent.com/10344542/90656795-aa50f880-e26c-11ea-8df1-fa65dbc8ab1a.png)

**Comment by pirey** [comment]
turns out the symfony/console version conflicted with requirement from another global composer package i installed.

i managed to resolve the issue by updating global packages.

thanks.
